### ISSUE TITLE
최명기 연구 과제

### ISSUE THREAD

**Issue by shanmdphd** [pipetcpt/trainees#3]
@mante111 선생님

1. 아무 Rmarkdown 문서를 만들고 
2. html 파일을 생성하여, 
3. https://github.com/pipetcpt/interns/tree/master/2020-homework 에 Rmd와 html 파일을 올려주세요. (기한 2019-12-27)

**참고링크**

1. https://tariat.tistory.com/663
1. https://github.com/pipetcpt/interns/tree/master/2019-homework

**Comment by shanmdphd** [comment]
1. https://github.com/pipetcpt/interns/tree/master/docs-presentation 의 R과 그 패키지와 관련된 이론을 습득하고 실습해 보십시오.
2. 그 후에 https://github.com/pipetcpt/interns/tree/master/2019-homework 의 *.Rmd 에 대하여 *.html로 변환하면서 그 의미를 파악하십시오.

**Comment by shanmdphd** [comment]
선생님이 이제 R이 익숙해졌으므로 본격적으로 약리학에 응용할 수 있을 것입니다. 아래 자료를 참고해서 비구획분석을 R로 수행해보세요.

- https://asancpt.github.io/book-ncar
- [4-Pil-NCA-using-R-handout.pdf](https://github.com/pipetcpt/interns/files/4011807/4-Pil-NCA-using-R-handout.pdf)
- [3-4-Pil-NCA-using-Excel-R-presentation.pdf](https://github.com/pipetcpt/interns/files/4011808/3-4-Pil-NCA-using-Excel-R-presentation.pdf)

**Comment by mante111** [comment]
1. tblNCA에서 iAUC랑 R2ADJ항을 넣으면 오류가뜨는데 왜 그런지 모르겠습니다.
2. NonCompart에 여러가지 함수가 있다고했는데 글에서는 AUC만 설명되어있는데 이것만 알면 되나요??
3. tibble이라는 명령어가 어떤건지 잘모르겠습니다.

**Comment by shanmdphd** [comment]
tblNCA에서 iAUC랑 R2ADJ항을 넣으면 오류가뜨는데 왜 그런지 모르겠습니다.
iAUC는 interval AUC의 약자로 구간의 AUC를 구하는 것인데 패키지에서 아직 개발이 진행되고 있는 것 같습니다.
R2ADJ의 오류 나는 것을 

    NonCompart에 여러가지 함수가 있다고했는데 글에서는 AUC만 설명되어있는데 이것만 알면 되나요??

    tibble이라는 명령어가 어떤건지 잘모르겠습니다.

**Comment by shanmdphd** [comment]
선생님 언제까지 나오시게 되는 건가요? 논문을 한편 드릴테니 읽고 마지막 날에 발표하는 시간을 가졌으면 합니다. 

또한 임상시험 자료를 전자화해서 자료 분석하는 업무를 했으면 좋겠습니다.

**Comment by mante111** [comment]
네네 논문이랑 임상시험 자료 주시면 한번 해보겠습니다.

배울수 있는게 남아있다면 2월까지 나올 생각입니다,

**Comment by shanmdphd** [comment]
data-raw/assay/ 의 자료로 

1. 그림을 그려보고,
1. NCA 분석 수행해보세요.

**Comment by shanmdphd** [comment]
질문은 이곳에 해 주시고, 작업한 R 파일을 저장해서 아래 위치에 올려주세요.

https://github.com/pipetcpt/interns/tree/master/2020-homework

**Comment by mante111** [comment]
### 1. 주어진 자료에 성별항목이 없어 T-test를 할수가 없습니다. 
### 2. 주어진 자료에서 gene가 의미하는 것을 모르겠습니다.
### 3. 아래의 두 코드가 오류가 납니다.
```r
plotPK(PK_data, "ID", "TIME", "DV", unitConc = "ug/L", unitTime = "h")
```
```r
NCA <- tblNCA(PK_data, "ID", "TIME", "DV", doseUnit = "mg", timeUnit = "h", concUnit = "ug/L")
```

**Comment by shanmdphd** [comment]
1. Gene을 독립변수로 하여 ANOVA를 수행하세요.

**Comment by shanmdphd** [comment]
3. `PK_data <- read_excel("Drug_X_PK.xlsx") %>% as.data.frame()` 으로 해보세요.

**Comment by shanmdphd** [comment]
### 특정 ID 자료를 뺴는 법

```r
PK_data %>%
  filter(ID != 번호) # 번호는 숫자이거나 문자일 수 있음. 문자일 경우 "" 사용
```

**Comment by mante111** [comment]
* plotPK에서 이상한자료가 10번이길래 그거 찾아서 빼고 했는데도 안되서 모든항목에 대해서 plotPK를 해서 18번도 안된다는것을 찾았습니다. 그래서 10, 18번 자료 빼고 시행해봤는데 그래도 안되서 질문드립니다....

**Comment by shanmdphd** [comment]
네 선생님, 이와 관련된 질문은 이 곳에 달아주세요. plotPK는 오류가 나니 사용하지 마시고 진행해주세요

**Comment by mante111** [comment]
1. 주신 첫번째 과제에서 개인별로 그림을 그리려고 하는데 개인의 숫자가 너무 많아 for문을 사용하려고 하는데 어느 문법에 맞춰서 for문을 작성해야하나요??

* 그외의 부분은 다 작성해서 올리겠습니다.

**Comment by shanmdphd** [comment]
`+ facet_wrap(.~ID)` 을 사용해보세요.

**Comment by mante111** [comment]
* rmd 파일로 작성하고 저장 했는데 글자가 깨져서 저장되고 html파일이 생성이 되지 않습니다.

**Comment by mante111** [comment]
1. ggplot으로 plotting을 했고 정상처리 됬는데 plot창에 plot이 뜨지 않습니다.
2, 아래의 코드가 작동이 되지 않습니다.
```r
PK <- read_excel("CPT2019-02-CRF-data.xlsx", sheet = 11)
tblNCA(PK, "등록번호", "시험시간", "virtual_conc", doseUnit = "mg", timeUnit = "h", concUnit = "ug/L", R2ADJ = 0.01)
```

**Comment by shanmdphd** [comment]
1. 코드 전체를 올려주세요. 
2. as.data.frame(PK) 처리하세요.
3. sub('H', '', time) 후 as.numeric()
4. 코드 전체를 올려주세요.

**Comment by mante111** [comment]
1. 아래의 코드가 안됩니다.
```r
PK_day2 <- read_excel("CPT2019-02-CRF-data.xlsx", sheet = 11) %>% as.data.frame() %>% filter(방문 == "Day 2") %>% sub('H', '', 시험시간)
```

**Comment by shanmdphd** [comment]
일단 한글로 된 column name은 R에서 처리가 쉽지 않습니다. Excel에서 영어로 바꾸고 해보세요.
