### ISSUE TITLE
최명기 연구 노트

### ISSUE THREAD

**Issue by shanmdphd** [pipetcpt/trainees#4]
## 마크다운 형태로 글쓰기

- @mante111 선생님 하루에 하신 일을 아래와 같이 댓글로 기록해 주세요.
    - 마크다운 형태를 사용하여 글을 써 보세요. (Edit 버튼 눌러서 raw text 확인할 것.)
    - 마크다운 형태로 글쓰는 것은 프로그래머에게 좋은 습관입니다.
    - 자료: https://github.com/pipetcpt/interns/wiki/Information-for-PIPET-Interns

![image](https://user-images.githubusercontent.com/6946821/71608316-a8460680-2bc3-11ea-98d5-96f535adb964.png)

## 원칙

- 주별로 하나의 reply에 edit하면서 작성하면 좋겠습니다. (위의 reply 참고. 제가 수정해 놓음)
- 매주 월요일 10시에 회의에서 작성한 reply를 보면서 진행을 보고해 주시면 좋을 것 같아요. (아울러 profile 사진을 하나 올려서 avatar가 표시되게 해주세요.)
- 위의 제목 옆에 Watching, Star 클릭해 주세요.

**Comment by mante111** [comment]
2019.12.31 (화)
오전 : R, dokyr, ggplot 복습
오후 비구획분석 공부

**Comment by mante111** [comment]
2020.1.02(목)
오전 : 비구획분석 공부 chapter5-7
오후 : 비구획분석 공부 chapter 8 및 PDF 파일 두개 학습

**Comment by shanmdphd** [comment]
![오토바이](http://www.ridemag.co.kr/news/photo/201909/13938_87373_4639.jpg)

**Comment by mante111** [comment]
## 2020.01.03(금)
* 오전 : 비구획 분석 복습
* 오후 : 
    *  아래 링크 chapter 1-6 학습
[링크](http://datamining.dongguk.ac.kr/lectures/R/_book/ggplot2.html)
    * 연구 과제

**Comment by mante111** [comment]
## 2020.01.06(금)
* 오전 : 회의 및 용어질문
* 오후 : 연구과제

**Comment by shanmdphd** [comment]
주별로 하나의 reply에 edit하면서 작성하면 좋겠습니다. (위의 reply 참고. 제가 수정해 놓음)

**Comment by mante111** [comment]
* ##### PK data 추출

**Comment by mante111** [comment]
## 2020.01.13(월)
* 오전 : 회의 및 용어질문
* 오후 
    * 모델링 기초 개념 공부
    * NONMEM basic 1 1장공부
 
## 2020.01.07(화)
* 오전 : 휴가
* 오후 : 휴가

## 2020.01.08(수)
* 오전 : CRF 문서화
    * 활력징후 2020-01-08
    * 심전도 2020-01-08
 
* 오후 : CRF 문서화
    * 등록서취득
    * 시험전 면담
    * 신체검사
    * 병력 및 수술력
    * 선정제외기준

## 2020.01.09(목)
* 오전 : CRF 문서화
    * 이상반응
    * 병용약물
    * 시험종료
    * 방문일
* 오후 :
    * 연구 과제 수행
    * 신약개발 스터디 참여 - Qfitter 회의실
## 2020.01.10(금)
* 오전 : Verapamil / Moxifloxacin NCA
* 오후
    * 회의 참여
    * CRF 문서화

**Comment by mante111** [comment]
## 2020.01.20(월)
* 오전 : 휴가
* 오후 : 휴가

 
## 2020.01.21(화)
* 오전 : 휴가
* 오후 : 휴가

## 2020.01.22(수)
* 오전 :   NONMEM basic 1 8장 공부
* 오후 : 
## 2020.01.16(목)
* 오전 : NONMEM basic 1 4장공부
* 오후 : NONMEM basic 1 5-6장공부

## 2020.01.17(금)
* 오전 :  NONMEM basic 1 7장 공부
* 오후
    * sw회의 참여 및 궁금증 질문
    *  digitizer 실습

**Comment by mante111** [comment]
## 2020.01.27(월)
* 오전 : 설휴가
* 오후 : 설휴가

 
## 2020.01.28(화)
* 오전 : NONMEM basic 1 동영상 1개 시청
* 오후 : 

## 2020.01.22(수)
* 오전 :   NONMEM basic 1 8장 공부
* 오후 :  NONMEM basic 1 동영상 2개 시청
## 2020.01.23(목)
* 오전 : 휴가
* 오후 : 휴가

## 2020.01.24(금)
* 설연휴

**Comment by mante111** [comment]
## 2020.02.3(월)
* 오전 : 계량약리 회의, sw 회의
* 오후 : pk 공부

 
## 2020.01.28(화)
* 오전 : NONMEM basic 1 동영상 1개 시청
* 오후 : NONMEM basic 1 복습

## 2020.01.29(수)
* 오전 :  휴가
* 오후 :  휴가

## 2020.01.30(목)
* 오전 : NONMEM basic 1 동영상 1개 시청
* 오후 : ct-db정리

## 2020.01.31(금)
* 오전 : ct-db정리
* 오전 : NCA용 data 편집

**Comment by mante111** [comment]
## 2020.02.10(월)
* 오전 : 계량약리 회의
* 오후 : pk 공부

 
## 2020.02.11(화)
* 오전 : pk 공부
* 오후 : pk 공부

## 2020.02.12(수)
* 오전 :  pk 공부
* 오후 :  verapamil NCA 분석용 데이터 만들기

## 2020.2.6(목)
* 오전 : pk 공부
* 오후 : pk 공부

## 2020.2.7(금)
* 오전 : pk 공부
* 오후 : NCA용 data 편집

**Comment by mante111** [comment]
## 2020.02.17(월)
* 오전 : 계량약리 회의
* 오후 : 논문읽기

 
## 2020.02.11(화)
* 오전 : pk 공부
* 오후 : pk 공부

## 2020.02.12(수)
* 오전 :  pk 공부
* 오후 :  pk 공부

## 2020.2.13(목)
* 오전 : 분주 업무
* 오후 : 분주 업무

## 2020.2.14(금)
* 오전 : 논문읽기
* 오후 : 논문읽기

**Comment by mante111** [comment]
## 2020.02.24(월)
* 오전 : 계량약리 회의
* 오후 : 휴가

 
## 2020.02.25(화)
* 오전 : 여행
* 오후 : 여행

## 2020.02.26(수)
* 오전 : 여행
* 오후 : 여행

## 2020.2.27(목)
* 오전 : 여행
* 오후 : 여행

## 2020.2.21(금)
* 오전 : 논문 발표준비
* 오후 : 논문 발표 준비
