### ISSUE TITLE
용어 설명

### ISSUE THREAD

**Issue by shanmdphd** [pipetcpt/trainees#5]
> ### 용어에 대해 질문이 있어 글올립니다. 
> 1. 모델링이랑 시뮬레이션이라는 용어가 나오는데 정확히 어떤 과정인지 궁금합니다.
> 2. 아래의 용어들이 궁금합니다.
>     * GHB
>     * ASCPT
>     * TMDD
>     * LLOq
>     * CV
>     * sad PK(정확하진 않은데 이런 느낌의 단어였습니다.)
>     * data set 만드는거에 대한 이야기나 나왔는데 data set 만드는게 그렇게 어려운일인가요?? 제 생각엔 엄청 어려울거 같진 않은데 오늘 문맥상으로는 할수 있냐고 많이 묻더라고요
> 

1. http://www.kddf.org/bbs/bbs.asp?mode=view&IDX=970&p=2&cateId=39 으로 답변 대신합니다.
2. 용어설명
    - GHB - https://www.hankyung.com/it/article/2019020170081
    - ASCPT - 미국임상약리회
    - TMDD - Target mediated drug disposition
    - LLOQ - 최저정량한계
    - CV - Coefficient of variation
    - SAD - Single ascending dose
    - Dataset - NONMEM dataset 만드는 특별한 규칙이 있고, 쉽지 않습니다.

**Comment by mante111** [comment]
아래의 용어의 의미가 궁금합니다.
* CSR
* CRA
* BST

**Comment by shanmdphd** [comment]
- CSR: Clinical Study Report
- CRA: Clinical Research Associate 
- BST: Blood Sugar Test

**Comment by mante111** [comment]
1. 아래의 용어의 의미가 궁금합니다.
* qw, q2w
* mma
2. km과 kd가 다르다고 하는게 어떻게 다른지 궁금합니다.

**Comment by shanmdphd** [comment]
QW - every week (매주)
Q2W - every other week (2주 마다)
MMA - 검색해 보세요. 문맥에 따라 여러 의미가 있을 것입니다.
Km / Kd -
https://www.sciencesnail.com/science/km-vs-kd-the-difference-between-michaelis-and-dissociation-constants
