### ISSUE TITLE
Verapamil / Moxifloxacin PK model

### ISSUE THREAD

**Issue by shanmdphd** [pipetcpt/trainees#6]
@mante111 님,

Verapamil / Moxifloxacin PK model 을 찾아보세요.

- pubmed.gov 에서 검색
- google 에서 검색

**Comment by mante111** [comment]
* [Verapamil](https://bpspubs.onlinelibrary.wiley.com/doi/pdf/10.1111/j.1365-2125.1992.tb04091.x)
* [Moxifloxacin](file:///C:/Users/OASIS02/Downloads/P1745.pdf)

**Comment by shanmdphd** [comment]
Moxifloxacin 의 투여경로가 IV인데 oral 인 모델을 찾아보세요.

**Comment by mante111** [comment]
1. 띄워쓰기가 들어간 변수값은 R에서 어떻게 처리해야 하나요??
2. 특정 범위의 행의 값을 바꾸고 싶은 경우 쓸수 있는 명령어가 있나요??
3. 행이나 열을 지울수 있는 명령어가 있나요??

**Comment by mante111** [comment]
``r
dasda
``

**Comment by shanmdphd** [comment]
```r
Atime <- read_excel("C:/mante111/R/CRF NCA 분석 데이터 만들기/atime.xlsx") %>% # CHECK: 영어 폴더이름 쓰세요.
  mutate(atime = ymd_hm(`atime`)) %>% 
  mutate(LastDosingTime =  ymd_hm(LastDosingTime)) %>% 
  mutate(dif = difftime(atime, LastDosingTime, units = "hours")) %>% 
  mutate(dif_ifelse= ifelse(dif < 0, 0, dif)) %>% 
  mutate(time = sub("H", '', time)) # CHECK: 이부분 수정하세요.
```
