### ISSUE TITLE
최명기 논문발표: DAC HYP - Modeling

### ISSUE THREAD

**Issue by shanmdphd** [pipetcpt/trainees#7]
다음 논문을 읽고 15분 발표자료를 준비해서 월요일 미팅에서 발표했으면 좋겠습니다.

https://www.ncbi.nlm.nih.gov/pubmed/27333593

[Diao_et_al-2016-British_Journal_of_Clinical_Pharmacology.pdf](https://github.com/pipetcpt/interns/files/4196386/Diao_et_al-2016-British_Journal_of_Clinical_Pharmacology.pdf)

**Comment by shanmdphd** [comment]
궁금한 점은 여기 댓글로 달아주세요.
발표자료는 준비되는대로 https://github.com/pipetcpt/interns/tree/master/docs-presentation  올려주세요.

**Comment by mante111** [comment]
1. plateau에 도달햇다는 것을 steady state랑 같은 의미인가요??
2. 다발성 경화증을 치료 하려면 면역과민을 억제 해야하는데 Daclizumab HYP는  Treg를 억제하는 효과는 이와 상충되는거 같은데 제가 놓친부분이 있나요??
3. CD56bright natural killer을 잘몰라서 찾아봤는데 적응면역을 유발, NK세포 억제, 특수한 경우에서 면역억제를 한다고 하는데 제가 잘못 이해하거나 다른 특별한 특징이 있을까요??

**Comment by shanmdphd** [comment]
1. Plateau의 의미는 편평한 상태를 말하고 꼭 SS를 지칭하는게 아닐수도 있습니다.
2. DAC HYP는 CD25에 대한 항체이기 때문에 Treg도 억제됩니다. 면역과민의 억제가 Treg 경로만 있는게 아니라 다른 경로도 존재합니다. 
3. CD56br NK가 면역억제를 유도한다고 대략 이해하면 됩니다.

**Comment by mante111** [comment]
1. indirect response model, Treg trafficking이 무엇인지 모르겠습니다.

**Comment by shanmdphd** [comment]
1. http://mlxtran.lixoft.com/examples/pkpd-model-indirect-response/ 을 참고하세요. PK,  약물의 농도가 PD에 영향을 어떻게 미치는지를 표현하는 모델입니다. 생성억제, 생성촉진, 배출억제, 배출촉진 등에 따라 응답이 어떻게 달라지는지 눈여겨 보세요.

![image](https://user-images.githubusercontent.com/6946821/74707204-77499000-525c-11ea-928f-ccbe158678ed.png)

2. Treg이 면역억제가 필요한 장소로 이동하는 과정을 Treg trafficking이라고 합니다.

    the mechanism of the Treg effect by daclizumab HYP may be an indirect effect related to Treg trafficking, as opposed to direct effects on the development or survival of Tregs.

논문 내에서 위 문장에서 쓰인 것은 'DAC HYP가 Treg의 생존에 직접적인 영향을 미친다기 보다는 Treg의 이동과 연관된 간접적인 영향을 미친다' 정도로 보면 됩니다.

**Comment by mante111** [comment]
1. A covariance step was not successful for the final model, therefore, the % relative standard error for the parameters are not presented
이라는 문장이 무슨의미인지 모르겠습니다.


2. Population modelling predicted CD25 desaturation in patients whose serum daclizumab concentrations were in the lower fifth percentile for the low dose daclizumab group, but not the high dose daclizumab group.
이라는 문자의 의미를 모르겠습니다.


3. Subjects received either daclizumab HYP150 or 300 mg s.c. every 4 weeks for a total of 13 doses or placebo s.c. every 4 weeks for a total of five doses (24 week washout) 
여기서 5DOSE만큼 쉬었는데 왜 24주인지 모르겠습니다.
